/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.sv.ujmd.restaurante.formularios;

import edu.sv.ujmd.restaurante.clases.Alimentos;
import edu.sv.ujmd.restaurante.clases.Bebida;
import edu.sv.ujmd.restaurante.clases.Factura;
import edu.sv.ujmd.restaurante.util.CargarPropiedades;
import static edu.sv.ujmd.restaurante.util.CargarPropiedades.prop;
import edu.sv.ujmd.restaurante.util.ComboAlimentos;
import edu.sv.ujmd.restaurante.util.ComboBebidas;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author reyee
 */
public class Menu extends javax.swing.JFrame {

    
    String textoAlimento;
    String textoBebida;
    String cantidadAli;
    String cantidadBeb;
    String idAli;
    String idBeb;
    String precioAli;
    String precioBeb;
    Alimentos ali;
    Bebida beb;
    Factura fac;
    CargarPropiedades p;
    ComboAlimentos comboAli;
    ComboBebidas comboBeb;
    int indexComboAli = 0;
    int indexComboBeb = 0;
    DefaultComboBoxModel modeloComboAli = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloComboBeb = new DefaultComboBoxModel();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form Menu
     */
    public Menu() {
        try {
            p = new CargarPropiedades();
            ali = new Alimentos();
            beb = new Bebida();
            fac = new Factura();
            initComponents();
            comboAli = new ComboAlimentos();
            comboBeb = new ComboBebidas();
            
            setLocationRelativeTo(null);
            CargarTexto();
            CargarDatosLocal();
            llenarComboAli();
            llenarComboBebidas();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void CargarTexto() {
        this.lblAlimentos.setText(prop.getProperty("lblAlimentos"));
        this.lblBebidas.setText(prop.getProperty("lblBebidas"));
        this.lblCantidad.setText(prop.getProperty("lblCantidad"));
        
        
    }

    public void CargarDatosLocal() {

    }

    public void llenarComboAli() {
        try {
            ResultSet rs = ali.llenarCombo();
            modeloComboAli.addElement("Seleccione un campo");
            cboxAlimento.setModel(modeloComboAli);
            while (rs.next()) {
                comboAli.setId(rs.getInt(1));
                comboAli.setNombre(rs.getString(2));
                comboAli.setPrecio(rs.getFloat(3));
                modeloComboAli.addElement(comboAli.getId() + " - " + comboAli.getNombre() + " - " + comboAli.getPrecio());
                //  modeloCombo.addElement(new c_combo(rs.getInt(1),rs.getString(2)));
                // jComboBox1.setModel(modeloCombo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void llenarComboBebidas() {
        try {
            ResultSet rs = beb.llenarComboBebida();
            modeloComboBeb.addElement("Seleccione un campo");
            cboxBebidas.setModel(modeloComboBeb);
            while (rs.next()) {
                comboBeb.setId(rs.getInt(1));
                comboBeb.setNombre(rs.getString(2));
                comboBeb.setPrecio(rs.getFloat(3));
                modeloComboBeb.addElement(comboBeb.getId() + " - " + comboBeb.getNombre() + " - " + comboBeb.getPrecio());
                //  modeloCombo.addElement(new c_combo(rs.getInt(1),rs.getString(2)));
                // jComboBox1.setModel(modeloCombo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxAlimento = new javax.swing.JComboBox<>();
        lblAlimentos = new javax.swing.JLabel();
        lblcomboAli = new javax.swing.JLabel();
        lblBebidas = new javax.swing.JLabel();
        cboxBebidas = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        txtCantidadAli = new javax.swing.JTextField();
        txtCantidadBeb = new javax.swing.JTextField();
        btnCheckout = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblcomboBeb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboxAlimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxAlimento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxAlimentoItemStateChanged(evt);
            }
        });
        cboxAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxAlimentoActionPerformed(evt);
            }
        });

        lblAlimentos.setText(".");

        lblcomboAli.setText(".");

        lblBebidas.setText(".");

        cboxBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxBebidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxBebidasItemStateChanged(evt);
            }
        });
        cboxBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxBebidasActionPerformed(evt);
            }
        });

        lblCantidad.setText(".");

        txtCantidadAli.setName(""); // NOI18N

        btnCheckout.setText("Proceder a Carrito");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");

        lblcomboBeb.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblAlimentos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblBebidas)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lblCantidad)
                        .addContainerGap(279, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblcomboBeb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblcomboAli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(btnCheckout))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 230, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCantidadAli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidadBeb, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlimentos)
                    .addComponent(txtCantidadAli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcomboAli))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBebidas)
                    .addComponent(cboxBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadBeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcomboBeb))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckout)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCheckout.getAccessibleContext().setAccessibleName("Proceder a Carrito");
        btnCheckout.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cboxAlimentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxAlimentoItemStateChanged
        // TODO add your handling code here:
        
        lblcomboAli.setText((String) cboxAlimento.getSelectedItem());
        textoAlimento = lblcomboAli.getText();
        idAli = lblcomboAli.getText();
        
        idAli = idAli.substring(0, idAli.indexOf("-"));
        idAli = idAli.trim();
        lblcomboAli.setText(idAli);
        lblcomboAli.setText("id:" + idAli);
        indexComboAli = Integer.valueOf(idAli);
        
        
    }//GEN-LAST:event_cboxAlimentoItemStateChanged

    private void cboxAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxAlimentoActionPerformed

    private void cboxBebidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxBebidasItemStateChanged
        // TODO add your handling code here:
        
        String alimento;
        lblcomboBeb.setText((String) cboxBebidas.getSelectedItem());
        textoBebida = lblcomboBeb.getText();
        idBeb = lblcomboBeb.getText();
        
        idBeb = idBeb.substring(0, idBeb.indexOf("-"));
        idBeb = idBeb.trim();
        lblcomboBeb.setText(idBeb);
        lblcomboBeb.setText("id: " + idBeb);
        indexComboBeb = Integer.valueOf(idBeb);
        
        
    }//GEN-LAST:event_cboxBebidasItemStateChanged

    private void cboxBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxBebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxBebidasActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        
        
        
//        float Subtotal=0;
//        Subtotal = (Integer.parseInt(txtCantidadAli.getText())*comboAli.getPrecio())+(Integer.parseInt(txtCantidadBeb.getText())*comboBeb.getPrecio());
//        String resultado = null;
//        resultado = fac.IngresarDatos(
//            comboAli.getId(),
//            comboBeb.getId(),
//            Subtotal
//            
//            );
//        JOptionPane.showMessageDialog(null, resultado);
//    textoAlimento = modeloComboAli.getIndexOf(comboAli.getId());
    
//    
    Checkout checkout = new Checkout();
    checkout.setVisible(true);
    
    checkout.textAlimento=textoAlimento;
    checkout.textBebida=textoBebida;
    checkout.CantidadAlimentos=txtCantidadAli.getText();
    checkout.CantidadBebidas=txtCantidadBeb.getText();
    checkout.comboAli=comboAli;
    checkout.comboBeb=comboBeb;
    checkout.idAlimentos=idAli;
    checkout.idBebidas=idBeb;
    
    }//GEN-LAST:event_btnCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    public javax.swing.JComboBox<String> cboxAlimento;
    private javax.swing.JComboBox<String> cboxBebidas;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblAlimentos;
    private javax.swing.JLabel lblBebidas;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblcomboAli;
    private javax.swing.JLabel lblcomboBeb;
    private javax.swing.JTextField txtCantidadAli;
    private javax.swing.JTextField txtCantidadBeb;
    // End of variables declaration//GEN-END:variables
}
